### ISSUE TITLE
[REQUEST] Add bs.to Support

### ISSUE THREAD

**Issue by shedowe19** [wolfswolke/aniworld_scraper#44]
**Please describe what you want to be added/changed: Add bs.to Support**

@speedyconzales can you add Support for bs.to

**Comment by speedyconzales** [comment]
yeah I could. Already done it for myself, but I did not find it suitable for my needs because you will need an interactive browser window. That said I could not get it working in headless mode. 
And there are captchas from time to time, that you need to solve in order to get to the url of the content. Maybe I will try something else in the next days. But as of now it is more of a semi automated approach. That's why I don't like it

**Comment by shedowe19** [comment]
> yeah I could. Already done it for myself, but I did not find it suitable for my needs because you will need an interactive browser window. That said I could not get it working in headless mode. And there are captchas from time to time, that you need to solve in order to get to the url of the content. Maybe I will try something else in the next days. But as of now it is more of a semi automated approach. That's why I don't like it

Ahh okay Thanks, i wait ^^

**Comment by speedyconzales** [comment]
@shedowe19 you can try the current state of this https://github.com/speedyconzales/series-scraper
like I said I did manage to implement it in my current setup, but I don't feel like adapting my solution to the code structure of this repo -> basically because the underlying structure of the code did diverge too much
so there is bs.to support if you really need it (not headless and currently semi automated), but I don't know if it will be there within this repository too, so I decided to change the visibility of my repo to public

**Comment by speedyconzales** [comment]
Update: now also bs.to is working headless and completely automated
